<?php
/**
 * Created by PhpStorm.
 * User: murilo
 * Date: 20/11/16
 * Time: 19:30
 *
 * SOAP:
 *
 * DERIVED ACRONYM FOR SIMPLE OBJECT ACCESS PROTOCOL
 * VERSIONS 1.0 AND 1.1 RELEASED BY THE INDUSTRY; POPULARITY LED TO
 * CONTROL BY W3C WITH VERSION 1.2
 * EXTENSION USED TO WRITE SOAP SERVERS AND CLIENTS
 *
 * REQUIRES THE LIBXML EXTENSION (ENABLED BY DEFAULT IN PHP)
 *
 * RUNTIME CONFIGURATION
 * SOAP CACHE FUNCTIONS ARE AFFECTED BY php.ini SETTINGS (soap.wsdl_cache_*)
 *
 * SET OF PREDEFINED CONSTANTS AVAILABLE
 * AVAILABLE WHEN DYNAMICALLY LOADED AT RUNTIME OR WHEN COMPILED INTO PHP
 * PARTIAL LIST (ALL INTEGERS)
 * SOAP_1_1
 * SOAP_1_2
 * SOAP_ENCODED
 * SOAP_LITERAL
 * SOAP_AUTHENTICATION_
 * SOAP_ENC_*
 * SOAP_CACHE_*
 * SOAP_PERSISTENCE_*
 * SOAP_RPC
 *
 * SOAP FUNCTIONS
 * is_soap_fault CHECKS IF A SOAP CALL HAS FAILED
 * use_soap_error_handler INDICATES WHETHER TO USE AN ERROR HANDLER
 *
 */

