<?php
/**
 * Created by PhpStorm.
 * User: murilo
 * Date: 20/11/16
 * Time: 16:04
 *
 * EXTENSIONS:
 *
 * THERE ARE MANY ADD-ONS (EXTENSIONS) AVAILABLE FOR SPECIFIC PROGRAMMING TASKS
 * ADDED TO THE php.ini CONFIGURATION FILE
 * NEED TO CONFIGURE php.ini TO ACTIVATE THE EXTENSIONS YOU WANT TO
 * USE, AS WELL AS SPECIFY ALL THE NEEDED PATHS (EX: LIBRARIES)
 * NOT ALL EXTENSIONS CAN BE DISCUSSED WITHIN THIS GUIDE... PLEASE REVIEW
 * THE COMPLETE LISTING AVAILABLE IN THE PHP MANUAL (REFERENCE CITED BELOW)
 *
 *
 * PECL (PHP EXTENSION COMMUNITY LIBRARY):
 *
 * REPOSITORY FOR PHP EXTENSIONS; SIMILAR STRUCTURE AND CONCEPT TO THE
 * PHP CODE REPOSITORY PEAR (PHP EXTENSION AND APPLICATION REPOSITORY)
 *
 *
 * CORE EXTENSIONS:
 *
 * THERE ARE A SET OF VARIOUS PHP LANGUAGE ELEMENTS, CALLED CORE
 * EXTENSIONS, THAT ARE PART OF THE PHP CORE
 * THEY INCLUDE SPECIFIC ARRAYS, CLASSES, OBJECTS, ETC.
 *
 *
 * USERLAND RULES:
 *
 * USERLAND REFERS TO THOSE APPLICATIONS THAT RUN IN THE USER SPACE (NOT THE KERNEL)
 * SELECT RULES: (SEE THE COMPLETE LISTING IN THE PHP MANUAL)
 *
 */

// Some examples of PHP extensions:
// cURL
// JSON
// Mcrypt
// PDO
