<?php
/**
 * Created by PhpStorm.
 * User: murilo
 * Date: 20/11/16
 * Time: 19:13
 *
 * XML BASICS:
 *
 * XML IS ACRONYM FOR EXTENSIBLE MARKUP LANGUAGE
 * DATA FORMAT ("UNIVERSAL") USED FOR STRUCTURED DOCUMENT EXCHANGE
 * XML IS A LANGUAGE THAT PROVIDES THE MEANS FOR DESCRIBING DATA
 *
 */


