<?php
/**
 * Created by PhpStorm.
 * User: murilo
 * Date: 19/11/16
 * Time: 23:31
 *
 * OPERATOR PRECEDENCE:
 *
 * FOLLOWS MATHEMATICAL PRECEDENCE IN MOST INSTANCES
 * (EX:MULTIPLICATION/DIVISION PRECEDES ADDITION/SUBTRACTIONS)
 * USE PARENTHESES TO ENFORCE NON-STANDARD PRECEDENCE
 *
 */

echo 2 * 3 + 4; // outputs: 10
echo PHP_EOL;

echo 2 * (3 + 4); // outputs: 14
echo PHP_EOL;
